version: "3.9"

services:
  laravel-app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    image: peoplestats:1.0.0
    ports:
      - "8000:80"
    volumes:
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    env_file:
      - .env

volumes:
  storage_data:
  cache_data: